name: dev-env
services:
  postgres:
    image: "postgres:${POSTGRES_TAG:-latest}"
    container_name: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USERNAME:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data
  mongo:
    image: "mongo:${MONGO_TAG:-latest}"
    container_name: mongo
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME:-mongo}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD:-mongo}"
    volumes:
      - ./.volumes/mongo/db:/data/db
      - ./.volumes/mongo/configdb:/data/configdb
  redis:
    image: "redis:${REDIS_TAG:-latest}"
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./.volumes/redis/data:/data
    command: "redis-server --requirepass ${REDIS_PASSWORD:-redis}"
  rabbitmq:
    image: "rabbitmq:${RABBITMQ_TAG:-management}"
    container_name: rabbitmq
    restart: always
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USERNAME:-rabbitmq}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD:-rabbitmq}"
    volumes:
      - ./.volumes/rabbitmq:/var/lib/rabbitmq
  zookeeper:
    image: "confluentinc/cp-zookeeper:${ZOOKEEPER_TAG:-latest}"
    container_name: zookeeper
    restart: always
    ports:
      - "${ZOOKEEPER_PORT:-2181}:2181"
      - "${ZOOKEEPER_COMMANDS_PORT:-12181}:8080"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: "${ZOOKEEPER_TICK_TIME:-2000}"
  kafka:
    image: "confluentinc/cp-kafka:${KAFKA_TAG:-latest}"
    container_name: kafka
    depends_on:
      - zookeeper
    restart: always
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  kafka-ui:
    image: "provectuslabs/kafka-ui:${KAFKA_UI_TAG:-latest}"
    container_name: kafka-ui
    depends_on:
      - zookeeper
      - kafka
    restart: always
    ports:
      - "${KAFKA_UI_PORT:-19092}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: dev-env
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
  elasticsearch:
    image: "elasticsearch:${ELASTICSEARCH_TAG:-8.6.0}"
    container_name: elasticsearch
    restart: always
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
  kibana:
    image: "kibana:${KIBANA_TAG:-8.6.0}"
    container_name: kibana
    depends_on:
      - elasticsearch
    restart: always
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    environment:
      SERVER_NAME: dev-env
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
